export const mainColor = '#06eaea'
export const altColor = ' #0e63b496'
export const mainPaddingTop = '100px'
export const mainPaddingBottom = '100px'
export const sectionBackground = '#ececec'
export const mainTransition = '0.5s'